### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by beyarkay** [tcoppex/mbed-ble-hid#16]
Hi there, I'm just wondering what the state of this repo is? (abandoned, forgotten about, original author doesn't have enough time, etc). I saw the deprecation notice on the readme but can't see any information about why, so some info on that would also be great

I'm needing to use an Arduino Nano BLE as a keyboard for a year-long research project, so if someone can update me on current issues/problems or why the project was deprecated, that would be amazing. I have a fair amount of time to dedicate to making this a working interface and would love to do so, but don't really want to go in blind unless I have to.

Thanks!

**Comment by tcoppex** [comment]
Hi @beyarkay,

The problem was stated in a previous issue, basically a firmware / mbed OS upgrade made the lib deprecated and my attempts to solve this were unsuccessful. 

It is not dead per se but it is true I do not work on it on a consistent basis. You can check the last development on the dev branch [here](https://github.com/tcoppex/mbed-ble-hid/tree/dev) which is better but still not perfect. You are of course welcome to submit a PR if you find something and feel like it.

Cheers.

**Comment by beyarkay** [comment]
Okay thanks, I will check out the dev branch and see what I can do.
